- name: Ensure apt cache is up to date
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages
  ansible.builtin.apt:
    name:
      - unzip
      - git
    state: present

- name: Install pip for Python 3
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install PyMySQL module
  ansible.builtin.pip:
    name: PyMySQL
    state: present
